RecyThing/RecyThing-Web

- package-lock.json
- package.json
- src/App.jsx
- src/components/navigation/SearchBar.jsx
- src/components/navigation/SideBar.jsx
- src/components/navigation/index.js
- src/components/pagination/Pagination.jsx
- src/components/pagination/index.js
- src/components/tables/UserDetailTable.jsx
- src/components/tables/index.js
- src/configs/index.js
- src/configs/theme/index.js
- src/index.css
- src/main.jsx
- src/pages/AdminRoot.jsx
- src/pages/UserDetail.jsx
> feat(user-detail): add UI for user detail page and needed components

- src/assets/hamburger-active.svg
- src/assets/hamburger-non-active.svg
- src/components/navigation/NavBar.jsx
> add navbar

- netlify.toml
- src/pages/Login.jsx
> push (feat/login): add Login.jsx

- src/components/navigation/navbar/NavBar.css
- src/components/navigation/navbar/NavBar.jsx
- Sticky navbar
- add NavBar.css
- fix import img
- fix Nav li
> fix navbar

- src/components/modal/UserDetailModal.jsx
- src/pages/UserDetail.jsx
> refactor(user-detail-modal): update modal design based on latest UI

- src/components/footer/Footer.jsx
- refractor footer
- add hover
> feat(#001): Halaman Landing

- src/pages/AdminRoot.jsx
- src/pages/Dashboard.jsx
- src/pages/Download.jsx
add navigate on dashboard and download button
> feat(#007): Beranda Download Laporan

- .eslintrc.cjs
- jsconfig.json
- package-lock.json
- src/App.jsx
- src/components/inputs/Input.jsx
- src/components/inputs/InputWithLogo.jsx
- src/components/inputs/index.js
- src/components/modal/data-drop-point/CreateDataDropPointModal.jsx
- src/components/modal/data-drop-point/EditDataDropPointModal.jsx
- src/components/modal/data-drop-point/OperationalSchedule.jsx
- src/components/modal/index.js
- src/components/navigation/SearchBar.jsx
- src/components/tables/DataDropPointTable.jsx
- src/components/tables/base-table/TableCells.jsx
- src/configs/theme/index.js
- src/pages/DataDropPoint.jsx
> feat(data-drop-point): slicing ui for this feature (#014)

- src/components/modal/data-drop-point/DetailDataDropPointModal.jsx
- src/components/tables/DataDropPointTable.jsx
> feat(data-drop-point): add see detail ui (#014)

- src/pages/Login.jsx
> Feat (feat/login) : push update feat login Login.jsx (#002) 

- src/components/modal/data-customization/AddDataCustomizationModal.jsx
- src/components/modal/data-customization/EditDataCustomizationModal.jsx
- src/pages/DataCustomization.jsx
> feat(data-customization) : Update UI and filter button (#023)

- src/components/modal/waste-exchange-modals/WasteExchangeAddData.jsx
- src/components/modal/waste-exchange-modals/WasteExchangeDetailModal.jsx
- src/components/modal/waste-exchange-modals/WasteExchangeFormFields.jsx
- src/pages/ManageWasteExchange.jsx
Update UI, functions, and add waste exchange form fields
> feat(manage-waste-exchange) : Update UI, functions, and add waste exchange form fields (#022)

- .gitignore
- src/components/dashboard/RankingUser.jsx
- src/pages/Dashboard.jsx
> feat(finishing-dashboard-ui): Add Ranking in dashboard (#006)

- src/apis/APILogin.js
- src/components/navigation/dashboard/TopBar.jsx
- src/services/auth.service.js
> feat(integrate-data-admin): integrate data admin on topbar (#04) 

- src/apis/APICommunity.js
- src/apis/index.js
- src/components/modal/community/CommunityFormFields.jsx
- src/components/modal/community/CommunityFormSchema.js
- src/components/modal/community/ModalAddCommunity.jsx
- src/components/modal/community/ModalEditDetailCommunity.jsx
- src/components/modal/community/ModalViewDetailCommunity.jsx
- src/components/tables/community/TableCommunityList.jsx
- src/pages/Community.jsx
- src/store/community/createCommunitySlice.js
- src/store/community/deleteCommunitySlice.js
- src/store/community/fetchCommunitiesSlice.js
- src/store/community/fetchCommunitySlice.js
- src/store/community/index.js
- src/store/community/updateCommunitySlice.js
- src/store/index.js
add create, delete, update, view all, and view detail for community
> feat(api-integration): add api integration community (#021)

- src/components/inputs/Input.jsx
- src/components/modal/badge/BadgeFormFields.jsx
- src/components/modal/badge/ModalEditBadge.jsx
- src/components/tables/badge/TableBadgeList.jsx
- src/pages/Badge.jsx
> feat(badge): update add toast and spinner to modal badge when success #010

- src/apis/APIDashboard.js
- src/components/dashboard/Chart.jsx
- src/components/dashboard/FilterDropdown.jsx
- src/components/dashboard/InfoCard.jsx
- src/components/dashboard/LineGraph.jsx
- src/components/dashboard/RankingUser.jsx
- src/components/dashboard/Statistic.jsx
- src/pages/Dashboard.jsx
> feat(dashboard-filter): Add Filter yearly and monthly in dashboard with dummy data

- src/apis/APIApprovalMission.js
- src/apis/index.js
- src/components/modal/action-feedback/ModalApprove.jsx
- src/components/modal/action-feedback/ModalReject.jsx
- src/components/modal/mission-approval/ModalViewMissionApproval.jsx
- src/components/modal/mission-approval/TabButton.jsx
- src/components/modal/mission-approval/TabContent.jsx
- src/components/modal/transaction-list/ModalEditDetailTransaction.jsx
- src/components/tables/mission-approval/TableMissionApproval.jsx
- src/pages/MissionApproval.jsx
- src/store/approval-mission/fetchApprovalSlice.js
- src/store/approval-mission/fetchApprovalsSlice.js
- src/store/approval-mission/index.js
- src/store/approval-mission/updateApprovalSlice.js
- src/store/community/fetchCommunitySlice.js
- src/store/index.js
add view all, view detail, and update approval status api
> feat(api-integration): add api integration for mission approval (#017)

- src/pages/Login.jsx
> feat(login): update feature hide and seek in input form password #002

- src/apis/APIAchievements.js
- src/components/content-article/AddArticle.jsx
- src/components/modal/badge/BadgeFormFields.jsx
- src/components/tables/badge/TableBadgeList.jsx
> feat(badge): update feature table at bronze edit button #010

- src/components/navigation/landing-page/NavBar.jsx
- src/components/sections/download-section/DownloadSection.jsx
- src/pages/LandingPage.jsx
> feat(landing-page): update solved bug in navbar (#001)

- src/components/navigation/landing-page/NavBar.jsx
- src/pages/LandingPage.jsx
> feat (landing-page): update bug at navbar (#001)

- src/components/content-article/AddArticle.jsx
- src/components/modal/community/CommunityFormFields.jsx
- src/components/modal/community/CommunityFormSchema.js
- src/components/modal/event-community/CommunityEventFormSchema.js
- src/components/modal/event-community/EventCommunityFields.jsx
- src/components/modal/manage-admin/AdminFormFields.jsx
- src/components/modal/manage-admin/AdminFormSchema.js
- src/components/modal/mission-list/MissionFormFields.jsx
- src/components/modal/mission-list/MissionFormSchema.js
- src/components/modal/mission-list/ModalAddMission.jsx
- src/components/modal/mission-list/ModalEditMission.jsx
- src/components/modal/voucher-list/ModalAddVoucher.jsx
- src/components/modal/voucher-list/VoucherFormFields.jsx
- src/components/modal/voucher-list/VoucherFormSchema.js
- src/components/tables/community/TableCommunityList.jsx
- src/components/tables/manage-event-community/TableManageEventCommunity.jsx
- src/components/tables/mission-approval/TableMissionApproval.jsx
- src/components/tables/mission-list/TableMissionList.jsx
- src/components/tables/voucher-list/TableVoucherList.jsx
- src/pages/Community.jsx
- src/pages/ManageAdmin.jsx
- src/pages/ManageEventCommunity.jsx
- src/pages/MissionList.jsx
- src/pages/VoucherList.jsx
Fix Image Type :
- manage konten
- kelola misi
- manage reward
- komunitas
Have a some bug :
- kelola misi have a bug :
. pada saat nambah, jpeg sudah tidak bisa, akan tetapi jpg juga ga bisa, png bisa 
. pada saat edit jpeg sudah tersaring akan tetapi pas simpan toastnya berhasil diubah pas dibuka gambarnya tidak keubah
- manage reward / voucher tukar point
. tambah voucher setelah berhasil nambah ga ke close modalnya
. pada saat mau menambahkan yang baru data yang lama masih tertinggal
- komunitas
. tidak dapat memperbarui image
> FIX Image Type (#009, #012, #015, #021)
